version: "3"
# COMPOSE_TLS_VERSION=TLSv1_2
services:

  postgres:
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=pass"
      - "POSTGRES_DB=atlas"
    build: atlas-backend/db/
    volumes:
     - pg-vol:/var/lib/postgresql/data
  
  scraper:
    build: 
      context: atlas-backend/
      dockerfile: scraper-Dockerfile
    depends_on:
      - postgres

  webapp:
    ports:
      - "3000:3000"
    build: atlas-frontend/frontend
  
  app:
    build: 
      context: atlas-backend/
      dockerfile: app-Dockerfile

volumes:
  pg-vol:
    external: true
    

